# Generated by Django 4.2.20 on 2025-05-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=150)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('ccn3', models.CharField(max_length=3, unique=True)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('independent', models.BooleanField(default=True)),
                ('un_member', models.BooleanField(default=True)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.JSONField(default=list)),
                ('area', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('landlocked', models.BooleanField(default=False)),
                ('borders', models.JSONField(blank=True, default=list)),
                ('timezones', models.JSONField(default=list)),
                ('continents', models.JSONField(default=list)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('flag_png', models.URLField()),
                ('flag_svg', models.URLField()),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, null=True)),
                ('start_of_week', models.CharField(default='monday', max_length=10)),
                ('driving_side', models.CharField(default='right', max_length=10)),
                ('capital_latlng', models.JSONField(blank=True, null=True)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('google_maps', models.URLField()),
                ('open_street_maps', models.URLField()),
                ('tlds', models.JSONField(default=list)),
                ('alt_spellings', models.JSONField(default=list)),
                ('translations', models.JSONField(default=dict)),
                ('demonyms', models.JSONField(default=dict)),
                ('native_name', models.JSONField(default=dict)),
                ('languages', models.JSONField(default=list)),
                ('gini', models.JSONField(default=dict)),
                ('postal_code', models.JSONField(default=dict)),
                ('idd', models.JSONField(default=dict)),
                ('currencies', models.ManyToManyField(blank=True, to='countries.currency')),
            ],
        ),
    ]
