# Generated by Django 4.2.20 on 2025-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=255)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
