# Generated by Django 4.2.20 on 2025-05-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='ccn3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
